sudo: false
language: node_js
node_js:
- 'iojs'
notifications:
  email: simone.desordi@gmail.com
deploy:
  provider: heroku
  api_key:
    secure: IGTw1w9N7EyBq7lQr0jufazUnkTvMZ3lrNRS7msvxnP/uBVdPbAgkz9fQtJHtHfPkditnP/l4UXkaMFOTZ+42emLVj9Y+dCqLtqGA8Vlc7Hpx+yj+KLuEfhbwMRPVU9RBCDMgW7AZs+uTRw6V06jMZgMrll6d3wzJkZ7CfJ7H31xyZ3K41U/PtKO29dDf9GtrvUdw7UZtDmB1ltIxrtjtK5Ng6W/WXx4ybb22cDax+BfD2Cs68Kk/GAFfwFU4EEJg58CipSCnzCEqYFgj0+hFYF7ZcClD5CeUKGI6tVm0KAfaeyin0Pld5LnlLnydQGfcmh8lkzjKqeylimOdMpXEYZsRQYmtZpStvf8j0Mzq/LNd7y7rbOtpR352ZThgK5FL82d+pWxiHJxXeklrxPWPU6DyaeE+yIMaNwJ+04/Xy/7tE6K3xEfSr8YRJl96m36DQ8nEFTOsJrEkQpkqKX7wUOGU9YeZBHgbYmG7I6tkYsSW0amMVywlqDBO0WZAZdHdtBhqb2W++EHK6TV7IBQG2yq2AZkvoAOMyuScqcbs44N1Yu567dCV3ROehbyCxs07s3WTwwwAyHdTPYI2mG525UAyIWkpaEWysPGpL44p6KGN6PkmvT/ngCOGivjHyB2PRHHOsqoeGtb+I6tI2qWG8NYmFHIQqiMhomDjGw0BRQ=
  app: send-api
  on:
    repo: simonedesordi/send-api
